site_name: Poldoho's Homelab
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.top
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: lime

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Devices:
    - Asustor AS5404T: devices/tesseract.md
    - Raspberry Pi 4B: devices/wandapi.md
  - Services:
    - cAdvisor: services/cadvisor.md
    - Dockge: services/dockge.md
    - Grafana: services/grafana.md
    - Jellyfin: services/jellyfin.md
    - Node Exporter: services/nodeexporter.md
    - Portainer: services/portainer.md
    - Prometheus: services/prometheus.md
    - SNMP Exporter: services/snmpexporter.md
    - Tailscale: services/tailscale.md
    - Vaultwarden: services/vaultwarden.md